### PR TITLE
Adding activation note

### PR DESCRIPTION
**Pull request by julmot**
Issue described here: https://github.com/hammerjs/hammer.js/issues/870

### CODE REVIEW

**Comment by julmot** [comment]
@jtangelder Can you please merge this PR?

**Comment by julmot** [comment]
I will delete my fork in 2 months, so if no one merges this PR those changes will get lost.

**Comment by runspired** [comment]
@arschmitz can you get this brought in?

**Comment by julmot** [comment]
@arschmitz @runspired Bump

**Comment by arschmitz** [comment]
I'm on it sorry been busy getting releases out on other prijects

**Comment by julmot** [comment]
3 days remaining. @arschmitz don't answer, just click the "merge" button :smirk:

**Pull request merged**
